version: 2
jobs:
  build:
    docker:
      # https://circleci.com/docs/ja/2.0/circleci-images/#python
      - image: circleci/python:3.7.3
    branches:
        only:
          - master
    steps:
      - checkout
      - run:
            name: pip install 
            command: pip install -t ./python boto3==1.9.173
      - run:
            name: zip libraries 
            command: zip -r boto3-19173.zip python
      - run:
            name: deploy zip
            command: PYTHONPATH=./python python deploy.py boto3-19173
